### ISSUE TITLE
Release ARUtools 0.7.0

### ISSUE THREAD

**Issue by dhope** [ARUtools/ARUtools#39]
Tasks from high to low priority:
- [x] Fix #41 
- [x] Add ARU type detection by filemeta data (#34)
- [x] Add look around patterns (#6)
- [x] Pull timezone from filenames (#27)
- [x] Consider & implement reticulate (#5 )
- [x] Consider & implement robocopy (#26).
- [x] Remove "job" from `clip_wav()` (#25 )
- [x] wave lengths (#9)
- [x] Check logs and add features (#28 and #34)
- [x] Fix issue with no oversamples (#40)
- [x] Update vignettes for any changes above.

**Comment by dhope** [comment]
Merged into main.
